
[workspace]
channels = ["conda-forge"]
name = "napari-example"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

[pypi-dependencies]
# This will give you a released version
napari = { version = ">=0.6.2, <0.7", extras = ["all"] }
# Uncomment this and comment the line above if you want an editable install
# You should only use this from the root of napari's repo
#napari = { path=".", editable = true, extras=["all"]}

